"""empty message

Revision ID: 73fdb4da48ba
Revises: 
Create Date: 2025-10-02 12:53:05.333120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fdb4da48ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('doc_mob', sa.String(length=20), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('reg_no', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_mob'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reg_no')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('mob_no', sa.String(length=30), nullable=True),
    sa.Column('date_of_entry', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advice_timestamp'), ['timestamp'], unique=False)

    op.create_table('advice_drugs',
    sa.Column('advice_id', sa.Integer(), nullable=True),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advice_id'], ['advice.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advice_drugs')
    with op.batch_alter_table('advice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advice_timestamp'))

    op.drop_table('advice')
    op.drop_table('patient')
    op.drop_table('user')
    op.drop_table('drug')
    # ### end Alembic commands ###
